version: '3'
services:
  cesrv:
    restart: always
    build: ./cesrv
    ports:
      - "7000:7000"
    volumes:
      - "schema:/usr/src/app/catalog/schema"
    env_file: .env
    command: /usr/local/bin/gunicorn -t 180 -w 4 -b :7000 app:app
    networks:
      - net3

volumes:
  schema:

networks:
  net3:
    external: true
